#!/bin/bash

FILENAME="infodisplay"
URL="https://raw.githubusercontent.com/Watchedfungus88/scriptsvault/main/${FILENAME}"

curl -fsLO "$URL"

if [ $? -ne 0 ]; then
  echo "Error: Failed to download ${FILENAME}"
  exit 1
fi

chmod +x "$FILENAME"
if [ $? -ne 0 ]; then
  echo "Error: Failed to make ${FILENAME} executable."
  rm -f "$FILENAME"
  exit 1
fi

./"$FILENAME"
EXEC_STATUS=$?

rm -f "$FILENAME"

exit $EXEC_STATUS

